# Generated by Django 4.0.6 on 2022-07-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0003_aboutservices_fun_partners_reviews_team_typeworks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoweare', models.CharField(max_length=200)),
                ('whatwedo', models.CharField(max_length=200)),
                ('whywedoit', models.CharField(max_length=200)),
                ('sincewhen', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutServices',
        ),
    ]
