# Generated by Django 4.0.6 on 2022-07-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0004_settings_delete_aboutservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Genre',
            new_name='genre',
        ),
    ]
