# Generated by Django 4.0.6 on 2022-07-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0005_rename_genre_team_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
