# Generated by Django 4.0.6 on 2022-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0006_alter_partners_photo_alter_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/works/'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/partners/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/team/'),
        ),
    ]
