# Generated by Django 4.0.6 on 2023-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0008_works_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='images/works/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.RemoveField(
            model_name='works',
            name='type',
        ),
        migrations.DeleteModel(
            name='TypeWorks',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
