# Generated by Django 4.0.6 on 2023-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0010_setting_file_alter_team_genre_alter_team_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
