# Generated by Django 4.0.6 on 2023-01-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0011_header_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('characteristic', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=200)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('characteristic', models.ManyToManyField(to='homme.characteristic')),
            ],
        ),
    ]
