# Generated by Django 4.0.6 on 2023-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0012_characteristic_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
