# Generated by Django 4.0.6 on 2023-01-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0014_alter_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homme.service'),
        ),
        migrations.AlterField(
            model_name='price',
            name='characteristic',
            field=models.ManyToManyField(null=True, to='homme.characteristic'),
        ),
    ]
