# Generated by Django 4.0.6 on 2023-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0015_price_service_alter_price_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
