# Generated by Django 4.0.6 on 2023-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0016_price_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
