# Generated by Django 4.0.6 on 2023-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0017_price_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
