# Generated by Django 4.0.6 on 2023-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0019_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('count', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
