# Generated by Django 4.0.6 on 2023-01-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homme', '0020_counterup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterup',
            name='count',
            field=models.IntegerField(),
        ),
    ]
